export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const METRICS_DATA_RECEIVED = "METRICS_DATA_RECEIVED";
export const MEASUREMENTS_DATA_RECEIVED = "MEASUREMENTS_DATA_RECEIVED";
